language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.1"
  - iojs
notifications:
  email:
    on_success: always
    on_failure: always
env: BROWSERS=firefox E2E_BROWSERS=Firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm -g install npm@latest-2
before_install:
   - "gem install --version 0.8.9 faraday"
