language: node_js
sudo: false
node_js:
  - "4.0"
  - "4.4"
  - "5.0"
  - "stable"
notifications:
  email:
    on_success: always
    on_failure: always
env: BROWSERS=firefox E2E_BROWSERS=Firefox
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm -g install npm@latest-2
  - "gem install --version 0.8.9 faraday"
after_script: "cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
