language: java
jdk:
  - oraclejdk7
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
   - "gem install --version 0.8.9 faraday"
install: "echo 'No install command here!'"
script: "mvn install -B"
